---
name: Build, Test and Release Container

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "10 2 * * 0"

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Ansible Installation - Previous - ansible in the built image.
        run: docker build -t test-container:local -f Dockerfile .

      - name: Verify Ansible Installation - Previous - ansible in the built image.
        run: docker run --name test-container --rm test-container:local /opt/molecule/previous/bin/ansible --version

      - name: Verify Ansible Installation - Current - ansible in the built image.
        run: docker run --name test-container --rm test-container:local /opt/molecule/current/bin/ansible --version

      - name: Verify Ansible Installation - Next - ansible in the built image.
        run: docker run --name test-container --rm test-container:local /opt/molecule/development/bin/ansible --version

  docker-build:
    runs-on: ubuntu-latest
    needs: docker-test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64
          push: true
          pull: true
          tags: |
            ${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:latest
